version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "5800:5800"
    environment:
      PRISMA_CONFIG: |
        port: 5800
        databases:
          default:
            connector: mongo
            uri: 'mongodb://prisma:prisma@mongo'
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "5900:5900"
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "5900:5900"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: